"""The canonical registry of what this module guarantees.

**ONE SOURCE, THREE CONSUMERS.** ``conftest.py`` requires every registered id to
have RUN; ``scripts/fail_controls.py`` requires every registered id to have a
control PROVEN TO FAIL and refuses to run if one has none; ``docs/CONTRACT.md``
is generated from this file. A guarantee therefore cannot be quietly dropped from
any of the three, and a number of them cannot go stale in a comment, because
nothing types the number anywhere.

**A GUARANTEE IS A SENTENCE SOMEBODY COULD ACT ON.** Not "the validator checks
the terms" -- that is a description of a mechanism. "A contradiction between two
terms is refused when the pass is created, naming the field, and no contradiction
is ever resolved at the access call" is a claim with a failing case, and the
failing case is what the control plants.
"""

from __future__ import annotations

GUARANTEES: dict[str, str] = {
    "G1": (
        "ONE CAR, ONE PASS PER GARAGE -- AT EVERY GARAGE THE PASS NAMES, TOGETHER OR NOT "
        "AT ALL. A vehicle identity is registered to one pass "
        "at a garage for any given day; a second registration overlapping it is "
        "refused BY NAME, naming the garage, the pass that holds the identity, its state "
        "and the day that registration ends, BEFORE the database constraint has to -- every "
        "open registration is a holder whatever its pass's state -- and a refusal "
        "writes nothing. A registration is written at every garage the pass names, one row "
        "per garage in one transaction: a pass over three garages holds the car at all three "
        "from one enrolment, a car held by another pass at ANY of them refuses the whole "
        "registration by name, and a partial fan-out is never an outcome -- the EXCLUDE "
        "backstops each garage and a violation at any one takes every row of the fan-out "
        "back with it. Ending a registration ends it at every garage of the pass. The TARGET "
        "pass's state is read: a registration onto a "
        "suspended, revoked or expired pass is refused by name, naming the state; "
        "draft, awaiting enrolment and active take registrations. The database's "
        "EXCLUDE is the backstop for a raw insert and for two registrations "
        "genuinely racing -- in either shape the race takes, the constraint firing or "
        "the database rolling one writer back, the loser is refused by the constraint's "
        "name and never a traceback -- and is reached through the module by nothing "
        "else. Ending "
        "a registration on day D frees the identity FROM D: a registration elsewhere "
        "effective D is accepted, and the old pass covers the vehicle up to and not "
        "including D."
    ),
    "G2": (
        "Contradictory terms are refused AT CREATION, naming the field: a valid_to "
        "before valid_from, a window that no day in the valid range can satisfy, an "
        "empty window, a maximum stay of zero, a visit allowance of zero, a per-window "
        "allowance with no windows, no direction, an empty lane set -- and ONLY "
        "contradictions: a maximum stay longer than a window is slack, not a "
        "contradiction (windows bind instants, not stays), and such a pass is created "
        "and its maximum binds at the exit. A Terms value that fails the check cannot "
        "be constructed, so the access call never meets a contradiction. The schema's "
        "CHECKs back the single-table rules for a raw write; the three that span two "
        "tables are named in the migration and backed by the load path (G17)."
    ),
    "G3": (
        "No fee, no amount, no balance and no barrier command ever crosses the access "
        "call: the answer's fields carry none, the schema has no money-shaped or "
        "reservation-shaped column, and a document with a field this module does not "
        "know is refused rather than ignored. This module never opens or closes a "
        "gate and never counts who is inside."
    ),
    "G4": (
        "AN EXIT IS NEVER REFUSED, AND EVERY EXIT IS ANSWERED. No term, no state, no "
        "revocation and no inconsistency in the data refuses an exit to a vehicle that "
        "is inside, or fails to answer it: every exit produces a stated COVERED or "
        "NOT-COVERED answer -- refused-to-answer is not an outcome an exit can have, "
        "and the absence of an answer, a refusal and an exception on any data are each "
        "a failure of this guarantee. Whatever cannot be evaluated at an exit is NAMED, "
        "never guessed: a blank identity or lane, an unmeasurable maximum stay, an "
        "unreadable pass or garage, two passes holding one car, a registration naming a "
        "pass that was not handed in, a pass handed in twice under one id -- which is "
        "never resolved by the order the copies arrived in: every copy is evaluated, the "
        "holder is covered if any copy covers, and the same inputs in any order give the "
        "same answer. Every exit answer carries the sentence that says so, a not-covered "
        "exit means OUT-OF-TERMS and never a refusal, in every state including revoked, "
        "and the exit half of the call does not read the garage's transient mode. What "
        "remains outside this sentence is named because it cannot be otherwise, and it "
        "is a CLASS proven closed by execution, not a list: a value of a type the "
        "signature does not accept -- for any parameter of access(), or any element of "
        "its sequences, an instant with no timezone among them -- raises on the first "
        "touch, before there is an instant, a pass or an answer to give, and never "
        "answers (a wrong-typed value that answered would be a defect, not an "
        "exclusion; the test enumerates the signature and proves each one raises); and "
        "one ENVIRONMENT error -- a machine with no timezone database at all -- which is "
        "raised by its own name, never as an unknown zone. THE MODULE ANSWERS WHEN IT "
        "HOLDS A RECORD WHOSE CONTENT IT CANNOT READ, AND REFUSES WHEN IT HOLDS NO RECORD "
        "AT ALL, OR NO INSTANT TO READ IT AT: a stored row it cannot read loads unreadable "
        "and answers, and a DOCUMENT it cannot read -- a field missing, of the wrong type "
        "or unknown, a contradiction, an unknown zone -- is answered at an exit the same "
        "way, a pass or garage document degrading to the unreadable pass or garage a "
        "stored row becomes and a registration or visit document to a not-covered answer "
        "naming the document and the field (RECORD_UNREADABLE); at an entry the same "
        "document is refused by name. A file that is missing or is not JSON, and an "
        "instant that does not parse, are refused in both directions: no record, or no "
        "instant. A garage carrying a timezone this system does not carry cannot be "
        "constructed through the pure API, and neither can a registration or visit with "
        "a wrong-typed field."
    ),
    "G5": (
        "A revoked pass is refused at ENTRY in every configuration of terms, and "
        "revocation is terminal: no transition leaves revoked, and revoking a pass "
        "ends its registrations on the revocation day in the local calendar of EACH "
        "GARAGE THE PASS NAMES -- the rows at each garage on that garage's day of the "
        "instant, never on the day at the garage the command was typed from -- so the "
        "identity is free from that day there; every garage's day is derived before the "
        "first row changes, so a garage of the pass whose stored zone cannot be read "
        "refuses the revocation by name and nothing is half-ended."
    ),
    "G6": (
        "A garage that has not stated whether transient parking is available makes "
        "the access call REFUSE TO ANSWER at entry, naming the field. There is no "
        "default and no inference; the store keeps the field nullable so that unstated "
        "is a state and not a false."
    ),
    "G7": (
        "Terms evaluate in the GARAGE'S LOCAL DAY: a window's minutes are the garage's "
        "wall clock and its days are the garage's weekdays, measured at the window "
        "edges on the spring-forward and fall-back days where a UTC reading disagrees; "
        "and a stay's length is elapsed time between instants, computed in UTC, so a "
        "stay across the fall-back hour is an hour longer than its wall clocks say."
    ),
    "G8": (
        "An unknown vehicle identity gets a STATED answer -- not covered, NO_PASS, "
        "with the nearest ended or future registration named when there is one -- "
        "never an accidental refusal and never a silent pass. A BLANK identity is "
        "refused an answer AT AN ENTRY, naming the field, because there is nothing to "
        "look up; at an exit the same input is answered not-covered, naming the field."
    ),
    "G9": (
        "A visit allowance and a maximum stay are computed from the module's OWN "
        "recorded visits and from nothing else, and the answer names its denominator: "
        "how many entries were counted, on which pass, over its life or in which "
        "window on which day -- EACH ENTRY READ IN THE LOCAL DAY OF THE GARAGE IT WAS "
        "RECORDED AT, the count naming how many at each, because a pass's garages can "
        "stand in different zones and the wall clock an entry fell in is the one on the "
        "door it drove through (the LIFE allowance reads no clock); and which entry a "
        "stay was measured from -- the one recorded "
        "AT THE GARAGE THE CAR IS LEAVING, never an entry open at another garage of the "
        "pass -- both instants rendered as the garage's wall clock whatever offset each "
        "arrived with. A maximum stay with no open recorded entry AT THIS GARAGE to "
        "measure from is UNMEASURED and the "
        "answer says so by name while answering on the terms that can be evaluated -- "
        "never silently treated as satisfied, and never a refusal."
    ),
    "G10": (
        "Row-level security on every table from migration 0001: a tenant column, "
        "ENABLE, FORCE and a policy on each, read from the catalogue and never from a "
        "list; isolation proven ON EVERY TENANT-BEARING TABLE, from the catalogue, by a "
        "role that COULD bypass being shown it cannot read or write another tenant's "
        "rows -- and a stripped predicate on any one of the tables reddens it, every table "
        "of every migration having that control; "
        "and every garage and pass reference is half of a composite tenant key, so a "
        "row cannot name another tenant's garage or pass even by a raw insert."
    ),
    "G11": (
        "Nothing real in the tree: no email address that is not obviously invented, "
        "no card-shaped value, and no name from the maintainer's other software, in "
        "any file git tracks -- swept in Python over `git ls-files` with a positive "
        "control that fires before the result is read, and by CI guards that "
        "self-test the same way."
    ),
    "G12": (
        "Every state change records WHO, WHEN and WHY, none blank, into an "
        "append-only history: the application role holds SELECT and INSERT on it and "
        "nothing else, read from the catalogue and proven by a refused UPDATE -- and "
        "HOLDS DELETE ON NO TABLE IN THE SCHEMA, every table read from the catalogue "
        "with no hand list and no walk to miss a leaf, so the history cannot be erased "
        "by deleting what it belongs to and no row anywhere can be erased by the "
        "application at all (the module issues no DELETE); where an offending table "
        "also cascades into a history, the failure says so, the walk kept beside the "
        "grant. The allowed transitions are the published ones, `expired` is derived "
        "from valid_to and refused if typed, and revoked outranks expiry. THE OPERATOR "
        "WRITES ON A GARAGE -- the timezone repair, which changes how every pass at the "
        "garage is read, and the enrols-at repair, which decides where a QR may be "
        "redeemed -- are recorded the same way: who, when, why, the old value and the "
        "new, into a second append-only history with the same grant and the same "
        "cascade rule; a repair with no who or no why is refused and changes nothing, "
        "and the enrols-at repair refuses the R1 contradiction (no transient, enrols at "
        "exit) by name exactly as creation does. The set of append-only histories is "
        "read from the catalogue (every table the application role may only SELECT and "
        "INSERT) and must be exactly the two published ones."
    ),
    "G13": (
        "THE LABEL IS ONLY A LABEL. 'Monthly', 'employee', 'vendor' and the rest are "
        "free text the owner types, and no behaviour keys off them. THE PROOF IS THE "
        "MATRIX: two passes that differ only in label answer identically across every "
        "state, direction and term, and its power is measured -- twelve spellings of a "
        "label-keyed branch are planted as its controls, and it catches every one that "
        "changes an answer. An AST scan also reports the spellings it knows (a "
        "comparison, a string predicate, a match) and is a report, not the proof: a "
        "scan that must know every way to read a string is the wrong instrument."
    ),
    "G14": (
        "The fixtures are capable of exercising what they claim: the shifting zone "
        "really shifts on the named transition days, the fixed zone really does not, "
        "and the terms matrix holds cases on both sides of every axis the access "
        "answer branches on."
    ),
    "G15": (
        "docs/CONTRACT.md is DERIVED: the guarantees, the refusals, the not-covered "
        "reasons, the barrier meanings, the answer fields, the states and transitions, "
        "the document keys and the worked example are generated from the registries "
        "and by running the module -- and the derivation is proven by plants that "
        "contradict the prose and require it to change, never by comparing two "
        "copies of the same claim."
    ),
    "G17": (
        "A stored pass or garage this module cannot read degrades to a STATED answer, "
        "never an exception: at an entry refused-to-answer naming the field, at an exit "
        "not-covered naming the pass and the field (which at a transient garage means "
        "chargeable, and is said so). Terms are re-validated on every load, so a raw row "
        "no CHECK can reach, or a validator tightened after the row was stored, strands "
        "the pass -- and a stranded pass still answers. A timezone the system does not "
        "carry is refused where the garage is written -- checked CASE-EXACTLY against "
        "the tz database's own name set, so the answer is the same on a case-insensitive "
        "filesystem and a case-sensitive one, and a machine with no tz database at all "
        "is named as that, never as an unknown zone -- and an existing bad row answers "
        "first, naming the field. A WRITE against an unreadable pass or an unreadable "
        "garage is refused by name, naming the refusal that made it unreadable -- "
        "except the one write that repairs it: a garage's timezone can be corrected, "
        "so an unreadable garage is never permanently unfixable."
    ),
    "G18": (
        "THE COMMAND LINE RENDERS A REFUSAL, NEVER A TRACEBACK. Every Refused the "
        "module raises -- an unknown timezone is one -- is printed as the JSON refusal "
        "naming the field and the value, with exit status 3; a document that cannot be "
        "read, an instant or a day that does not parse, a naive instant, and -- at an "
        "ENTRY -- a document field of the WRONG TYPE -- a missing identity, an object "
        "where an id belongs, a number where a list belongs, text where a list belongs "
        "(never reinterpreted as the list of its characters) -- are refused the same way, "
        "naming the field; at an EXIT a document whose content cannot be read is "
        "ANSWERED not-covered naming the field, because an exit is never refused (G4): "
        "every value a document carries is checked against the type the dataclass it "
        "loads into declares, derived from the annotation and not from a list, so a "
        "field added later is covered the day it is added. A database that does not "
        "connect is a sentence on stderr with exit 2 -- as is a machine with no timezone "
        "database at all, named as that and never as an unknown zone, and as is "
        "whatever the database driver raises that the store did not turn into a named "
        "refusal (an unmigrated database, a role without its grants, a DSN that is not "
        "one): one sentence with its SQLSTATE, mapped LAST, after every named refusal "
        "has had its chance, so a deadlock at the one-car-one-pass INSERT is still the "
        "refusal that carries PostgreSQL's DETAIL. A tenant nobody seeded is refused by "
        "name at its first write, not met at the foreign key. A value that starts with "
        "a dash (`--timezone -06:00`) reaches the module and is refused by name, not "
        "read by argparse as an option. Every raise in the package is enumerated by AST "
        "and classified as rendered at that boundary, as the machine's configuration, or "
        "as a programming error no command can reach -- a value of a type the signature "
        "does not accept is reachable only from the pure API and never from a command, "
        "because the document boundary refuses it first -- and the sweep names its "
        "denominator, the raise statements, since an exception born of an operator on "
        "a wrong-typed value is not one; an exception class in none of the three fails "
        "the suite until it is classified."
    ),
    "G16": (
        "No test module sits outside the guarantee registry: every test module "
        "carries a registered guarantee mark or is named in an empty allowance, a "
        "module that plants a defect may not be excused, and a registered guarantee "
        "whose test did not run and pass fails the whole run unless its id is named "
        "in a written-down allowance that CI leaves empty."
    ),
    "G19": (
        "ONE QR, ONE CAR, ONCE. An enrolment is a one-time credential: it binds exactly "
        "one vehicle identity -- the one the lane measured and handed in -- and is then "
        "TERMINAL; a redeemed or cancelled enrolment can never be redeemed again, and "
        "neither can an expired one (derived from starts_on and days_valid against the "
        "garage's local day, never typed) or one not yet started. Several outstanding "
        "enrolments on one pass are allowed and intended -- a pass may carry several "
        "vehicles -- and each redeems to one car and dies. A redemption is ONE "
        "TRANSACTION: the registration, the pass's move to active where it was not "
        "already (recorded, with the enrolment as the actor), the enrolment marked "
        "redeemed and the access answer -- all or none, under a savepoint that is rolled "
        "back on EVERY exception: a refusal, the module's own or the database's backstop, "
        "writes nothing and is carried in the answer; anything else writes nothing and "
        "SURFACES, so a QR cannot half-land and be used twice and a defect is never "
        "swallowed. ONE CREDENTIAL, ONE SPEND UNDER CONCURRENCY: two lanes presenting one "
        "token at once get exactly one bind. The pass row is locked first, then the "
        "credential row (one lock order everywhere), and the state, the expiry and the "
        "pass's registrability are re-read under those locks -- the primary; the spend "
        "carries state = 'issued' and asserts one row -- the backstop; and the suite "
        "measures each with the other removed. Written for READ COMMITTED, the store's "
        "default; a caller at a stricter level meets the serialization failure as the "
        "named refusal a deadlock gets. ONLY A STRUCTURAL EXCLUSION REFUSES THE BIND: a "
        "pass whose terms allow no movement in the direction the garage enrols at is "
        "refused by name, beside the lane refusal and after it, and the credential stays "
        "issued; temporal non-coverage -- a weekday pass on a Sunday, a valid_from ahead, "
        "a movement outside the hours -- still binds. days_valid is STATED, refused by "
        "name when absent, never defaulted. The holder link is the same primitive, used "
        "once, under the same locks. Revoking a pass takes the same lock order -- the pass "
        "row, its credentials, its registrations -- so a revocation racing a redemption in "
        "either order leaves no live registration and no issued credential on the revoked "
        "pass; it cancels every outstanding enrolment and holder link in the same "
        "transaction, and the redemption's own state check refuses a revoked pass even "
        "with that cancellation planted away."
    ),
    "G20": (
        "THE ENROLMENT OPENS NOTHING ON ITS OWN. The answer a redemption returns is the "
        "module's own access answer for that same movement, produced by calling the one "
        "access path on the rows as written -- never a second implementation and never "
        "a hand-built answer -- and it is identical to calling access with the same "
        "inputs after the bind. Where the garage enrols follows from whether it sells "
        "transient parking (R1): a garage with no transient enrols at entry, DERIVED, and "
        "need not state it; a transient garage states entry or exit, and unstated makes "
        "the redemption refuse to answer naming garage.enrols_at (garage.transient_available "
        "first, when that is unstated); no transient AND enrols at exit is a contradiction "
        "refused by name where the garage is created and where the field is repaired, "
        "with the schema's CHECK as the backstop for a raw write. A QR presented at the "
        "wrong end is refused by name, naming the end this garage enrols at."
    ),
    "G21": (
        "A REDEMPTION REFUSAL IS NEVER AN EXIT REFUSAL, AND EVERY REDEMPTION IS ANSWERED. "
        "The redemption call always returns an access answer for the movement -- "
        "including when the redemption itself is refused, whatever the refusal: an "
        "unknown, used, cancelled, expired or not-yet-started credential, the wrong end, "
        "a pass that is not registrable, a lane outside the pass's terms, a direction "
        "outside the pass's terms, an identity on another pass, an unreadable garage. At "
        "an exit lane that answer is covered or not-covered with the exit note, never "
        "refused-to-answer (G4 holds through the enrolment path); at an entry it is "
        "whatever access says. The census of every refusal kind at every lane end is "
        "reported N/N with zero unanswered exits. Every refusal door is also driven "
        "through the command line in-process, so the rendered-sentence collector reads "
        "each refusal's detail, and a falsehood assembled at run time in any of them "
        "reddens the suite."
    ),
    "G22": (
        "THE TYPED VEHICLE DESCRIPTION DECIDES NOTHING. It is the holder's own statement "
        "of the car they will bring, recorded on the enrolment; the identity that binds is "
        "what the lane measured. The module cannot compare an opaque identity to free "
        "text and does not pretend to: a mismatch is not a refusal, and enrolments that "
        "differ only in their description redeem identically -- the same outcome, the "
        "same refusal, the same answer -- across every description and every identity. "
        "THE PROOF IS THE MATRIX, and its power is measured: five spellings of a "
        "description-keyed branch are planted as its controls and each reddens it."
    ),
    "G23": (
        "THE TOKEN IS NEVER STORED AND NEVER RENDERED. Only its SHA-256 goes in the row; "
        "the plaintext is returned exactly once, by the issue call, and by nothing else -- "
        "not by a read, not by a listing, not in a refusal detail, not in an answer. "
        "Proven by scanning every column of every table in the catalogue, and every "
        "detail the module rendered, for tokens it issued -- with the digest as the "
        "positive control that the scan reads the column that holds it, and a planted "
        "sentence as the positive control that the rendered scan can see one, because a "
        "zero from an unproven scan is UNMEASURED, not clean. secrets and hashlib from "
        "the standard library; no dependency; no QR image."
    ),
    "G24": (
        "A HOLDER LINK WRITES holder_name AND holder_phone ON THE PASS, AND NOTHING ELSE. "
        "Not the email, not the label, not the terms, not the state, not the garage: every "
        "other column of the pass row is the same after the redemption as before, and a "
        "wider write reddens the test naming the column it should not have touched. "
        "Redeeming the link, once, writes those two, issues an enrolment for that pass "
        "with the link as the issuer, and spends the link -- one transaction. The "
        "vehicle description goes on the enrolment, not the pass. The owner-only path "
        "stands: an owner issues an enrolment without the holder ever using a link. No "
        "email is sent and no account or password exists: the module mints and records; "
        "delivering is the integrator's. The holder's text is text in any script; a "
        "control character in it is refused by name by the module's one text validator, "
        "never handed to the database driver, and the same rule holds for every id, lane, "
        "label and actor the module reads."
    ),
    "G25": (
        "A PASS ANSWERS ONLY AT THE GARAGES IT NAMES. A pass carries a non-empty SET of "
        "garages, stated by listing them -- never an 'everywhere' flag, never inferred, an "
        "empty set or a blank member refused at creation naming the field -- and every door "
        "reads that set by MEMBERSHIP: the access call selects a pass for a garage only if "
        "the pass names it (at both places a pass is read for its garage, the duplicated-id "
        "grouping and the by-id map), the store refuses to store a pass at a garage it does "
        "not name and to load it at one, and a QR or a holder link of the pass redeems at "
        "any garage of the set and at no other, refused by name elsewhere. The terms are ONE "
        "set on the pass, evaluated at whichever garage the car is at -- a 20-visit "
        "allowance is 20 on the pass, not 20 per garage -- except the lanes, which are "
        "stated PER GARAGE because lane A1 at two garages is two barriers: where lanes are "
        "stated every garage the pass names has its own set, refused at creation otherwise "
        "naming the garage, and the lane check at each garage reads its own set and no "
        "other. A pass's id is unique per tenant, not per garage. Migration 0004 BACKFILLS: "
        "every pass that existed keeps exactly the one garage it had and every lane row "
        "carries its own pass's garage; a lane row it cannot place makes it fail naming "
        "the count rather than drop the row, and two passes of one tenant sharing an id "
        "make it fail naming the id rather than pick a winner. THE VISIT LEDGER STAYS PER "
        "GARAGE: one open visit per vehicle per pass PER GARAGE, by the module's own check "
        "and by the database's index, so an entry at one garage of the set is never refused "
        "for a visit still open at another and an exit never closes another garage's visit "
        "-- while the allowance still counts every garage of the set, EACH ENTRY READ ON THE "
        "CLOCK OF THE GARAGE IT WAS RECORDED AT: the pass's garages reach the engine (the "
        "store hands in every garage of every pass it selected; the command line hands in "
        "--garages), a per-window count reads each entry's day and minute in its own "
        "garage's zone against the asking garage's day, and an entry at a garage whose "
        "clock is not there -- not handed in, handed in unreadable, handed in twice -- is "
        "refused by name at an entry, never read on the asking garage's clock and never "
        "dropped (no exit counts an allowance, so no exit reaches it) -- and that refusal "
        "names the entry it could not read by its ABSOLUTE instant, as UTC and said so, "
        "unrendered on that garage's wall clock because that is the clock it does not hold: "
        "never in the offset the value arrived with, which through the store is the database "
        "session's zone, the same bytes under any session zone. A visit's garage id is "
        "text through the module's one validator, as a garage's id and each member of the "
        "pass's set are -- stripped, so an entry recorded under an id with a scanner's "
        "trailing space matches the garage handed in under the stripped id and is counted; "
        "blank or carrying a control character it is refused by name at construction, "
        "naming visit.garage_id. And a membership row "
        "decides nothing recorded under it: removing a garage from a pass that holds a visit "
        "or a registration there fails by name (the keys are RESTRICT), never erases them; "
        "only the lanes stated at that garage go with it."
    ),
    "G26": (
        "A PASS CAN BE READ WHOLE, BY ANY READER, AND THE READ WRITES NOTHING. One verb, "
        "show-pass, with the arguments every store verb takes (--tenant, --garage, --pass-id), "
        "prints as JSON the pass id, its stored state, the garages it names (external ids, "
        "sorted) and EVERY registration of the pass, history included -- ended rows too -- "
        "each as the identity as stored, the garage's external id, effective_day, end_day and "
        "ended_reason; the library function under the verb is the same code the verb calls, "
        "never a second path. It answers that and nothing more: not the holder's name, phone "
        "or email, not the terms, not the label, nothing from enrolments or holder_links -- "
        "the reader needs the register, and personal data it does not need does not travel. "
        "The rows are selected by the pass alone, never through its garage set, so no row "
        "is dropped for its garage; and the database says such a row cannot exist: a "
        "registration names a garage the pass holds "
        "(vehicle_registrations_garage_of_pass, migration 0004, RESTRICT), so a raw insert "
        "at a garage outside the set is refused by the constraint and a membership row "
        "under a registration cannot be removed. The order is applied IN PYTHON, by code "
        "point -- identity, then effective day, then garage external id; the garage list the "
        "same way -- never by ORDER BY, because the database's collation orders the same "
        "text differently on macOS and on glibc and a reader on another machine must get "
        "the same bytes. A pass stored unreadable (G17) is still shown -- state, garages and "
        "registrations -- and the unreadable field is named with its code; a garage of the "
        "set stored with a timezone the running system does not carry stops no read, since "
        "the read uses no clock: the pass is shown and each such garage is named with its "
        "code. A pass that does not exist, or exists only at another tenant, is refused by "
        "name as every store verb refuses it; a garage the pass does not name is refused by "
        "name naming the set (G25 -- the read is not a way to look a pass up from a garage "
        "it does not answer at); a garage the tenant does not have is refused by name. The "
        "read writes nothing, proven by row counts and row digests of every table in the "
        "catalogue before and after, never by reading the code's order. Another tenant's "
        "pass with the same id is not shown, proven beside a known-shown control in the same "
        "run, and held twice: by the row policy and by the read's own tenant predicate, each "
        "proven to hold with the other removed. The token is not rendered by the read and "
        "neither is its digest (G23's rendered scan covers the verb, with a plant as its "
        "positive control). The module stays standalone: nothing in the verb, its output, "
        "the contract, the README or any refusal names any other module or any particular "
        "reader -- it is a read of a pass for any reader."
    ),
}


def guarantee_ids() -> tuple[str, ...]:
    """Sorted numerically, not lexically -- G10 follows G9, not G1."""
    return tuple(sorted(GUARANTEES, key=lambda g: int(g[1:])))


#: Naming an id here lets the suite finish with that guarantee unproven. It is a
#: DECISION somebody writes down, never a default -- CI names nothing, and a
#: guarantee that did not run and pass fails the run.
ALLOW_ENV = "GARAGE_PASS_ALLOW_UNRUN"
